name: CI Nix Flake

on:
  pull_request:

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  encom:
    name: build encom
    needs: validate
    uses: ./.github/workflows/build-host.yml
    with:
      host: encom
    permissions:
      contents: read
      security-events: write

  sauron:
    name: build sauron
    needs: validate
    uses: ./.github/workflows/build-host.yml
    with:
      host: sauron
    permissions:
      contents: read
      security-events: write
