name: Deploy Nix Hosts

on:
  push:
    branches:
      - main
      - nix

jobs:
  validate:
    name: Validate Nix Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Format Nix Flake
        working-directory: ./flake
        run: nix fmt

      - name: Validate Nix Flake
        working-directory: ./flake
        run: nix flake check

  deploy:
    name: Deploy Nix Hosts
    needs: validate
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale OIDC
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:gha

      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Deploy Nix Hosts
        working-directory: ./flake
        run: |
          nix run nixpkgs#deploy-rs -- \
            --flake .#deploy \
            --ssh-key ${{ secrets.DEPLOY_SSH_KEY }}
